import { Component, OnDestroy, OnInit } from '@angular/core';
import {
  AbstractControl,
  FormBuilder,
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  ValidationErrors,
  Validators,
  FormsModule
} from '@angular/forms';
import { Subject, Subscription } from 'rxjs';
import { debounceTime, distinctUntilChanged } from 'rxjs/operators';

import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzModalService } from 'ng-zorro-antd/modal';
import { NzSegmentedModule } from 'ng-zorro-antd/segmented';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { NzTooltipModule } from 'ng-zorro-antd/tooltip';

import { ModalIntroEnComponent } from '../../components/modal-intro-en/modal-intro-en.component';
import { ModalPreviewComponent } from '../../components/modal-preview/modal-preview.component';
import { ModalReproductionComponent } from '../../components/modal-reproduction/modal-reproduction.component';
import { GithubIssue, GithubService } from '../../services/github.service';
import { getBugTemplate, getFeatureTemplate, PREVENT_COPY_LINK, REP_LINK_REGEXP } from '../../util';

@Component({
  selector: 'app-issue-en',
  imports: [
    FormsModule,
    ReactiveFormsModule,
    NzButtonModule,
    NzFormModule,
    NzInputModule,
    NzSegmentedModule,
    NzSelectModule,
    NzTooltipModule
  ],
  templateUrl: './issue-en.component.html'
})
export class IssueEnComponent implements OnInit, OnDestroy {
  searchSubject$ = new Subject<string>();
  searchSubjection: Subscription | null = null;
  issueBugForm!: FormGroup;
  issueFeatureForm!: FormGroup;
  issueType = 'bug';
  confirmMarkdown = '';

  repositories = ['ng-zorro-antd'];
  features = [
    {
      label: 'Bug report',
      value: 'bug'
    },
    {
      label: 'Feature Request',
      value: 'feature'
    }
  ];

  versions: string[] = [];
  searchIssues: GithubIssue[] = [];

  replinkValidator = (control: FormControl): ValidationErrors | null => {
    if (!control.value) {
      return { error: true, required: true };
    } else if (!REP_LINK_REGEXP.test(control.value) || PREVENT_COPY_LINK.test(control.value)) {
      return { error: true, repLink: true };
    }
    return null;
  };

  getFormControl(name: string): AbstractControl {
    if (this.issueType === 'bug') {
      return this.issueBugForm.controls[name];
    } else {
      return this.issueFeatureForm.controls[name];
    }
  }

  /**
   * 更换issue type
   * @private
   */
  changeType(): void {
    this.searchSubject$.next('');
  }

  /**
   * 提交表单
   */
  submitForm(): void {
    const repo = this.getFormControl('repository').value;
    const label = this.issueType === 'feature' ? '&labels=type:feature' : '';
    this.confirmMarkdown = `${this.confirmMarkdown}\n\n<!-- generated by ng-zorro-issue-helper. DO NOT REMOVE -->`;
    const body = encodeURIComponent(this.confirmMarkdown).replace(/%2B/gi, '+');
    const title = encodeURIComponent(this.getFormControl('issue_title').value);
    window.open(`https://github.com/NG-ZORRO/${repo}/issues/new?title=${title}&body=${body}${label}`);
  }

  /**
   * 预览
   */
  submitFormPreview(): void {
    this.confirmMarkdown = '';
    let canPreview = false;
    if (this.issueType === 'bug') {
      for (const i in this.issueBugForm.controls) {
        this.issueBugForm.controls[i].markAsDirty();
        this.issueBugForm.controls[i].updateValueAndValidity();
      }
      if (!this.issueBugForm.invalid) {
        canPreview = true;
      }
    } else {
      for (const i in this.issueFeatureForm.controls) {
        this.issueFeatureForm.controls[i].markAsDirty();
        this.issueFeatureForm.controls[i].updateValueAndValidity();
      }
      if (!this.issueFeatureForm.invalid) {
        canPreview = true;
      }
    }
    if (canPreview) {
      switch (this.issueType) {
        case 'bug':
          this.confirmMarkdown = getBugTemplate(this.issueBugForm.value);
          break;
        case 'feature':
          this.confirmMarkdown = getFeatureTemplate(this.issueFeatureForm.value);
          break;
      }
      this.modalService.create({
        nzTitle: 'Preview Issue',
        nzMaskClosable: false,
        nzWidth: 680,
        nzContent: ModalPreviewComponent,
        nzOkText: 'Create',
        nzCancelText: null,
        nzStyle: {
          top: '40px'
        },
        nzData: {
          previewData: this.confirmMarkdown
        },
        nzOnOk: () => {
          this.submitForm();
        }
      });
    }
  }

  // 获取版本
  fetchReleases(): void {
    this._githubApiService.fetchReleases('NG-ZORRO', 'ng-zorro-antd').subscribe(data => {
      this.versions = data.map(item => item.tag_name).filter(tag => !!tag);
      this.issueBugForm.controls['version'].setValue(this.versions[0]);
    });
  }

  /**
   * 搜索
   * @param data
   */
  searchOnChange(data: string): void {
    this.searchSubject$.next(data);
  }

  /**
   * 弹窗提示
   */
  showIntro(): void {
    this.modalService.create({
      nzTitle: 'the reason behind our strict policy issue',
      nzMaskClosable: true,
      nzFooter: null,
      nzWidth: 680,
      nzContent: ModalIntroEnComponent
    });
  }

  /**
   * 复现链接说明
   */
  showReprod(): void {
    this.modalService.create({
      nzTitle: 'About Reproductions',
      nzMaskClosable: true,
      nzFooter: null,
      nzWidth: 680,
      nzContent: ModalReproductionComponent,
      nzData: {
        language: 'en'
      }
    });
  }

  constructor(
    private modalService: NzModalService,
    private fb: FormBuilder,
    private _githubApiService: GithubService
  ) {}

  ngOnInit(): void {
    this.issueBugForm = this.fb.group({
      repository: ['ng-zorro-antd', [Validators.required]],
      issue_title: ['', [Validators.required]],
      link: ['', [this.replinkValidator]],
      version: ['', [Validators.required]],
      environment: ['', [Validators.required]],
      step: ['', [Validators.required]],
      expect_result: ['', [Validators.required]],
      exist_result: ['', [Validators.required]],
      addition: ['']
    });
    this.issueFeatureForm = this.fb.group({
      repository: ['ng-zorro-antd', [Validators.required]],
      issue_title: ['', [Validators.required]],
      motivation: ['', [Validators.required]],
      proposal: ['', [Validators.required]]
    });
    // 版本
    this.fetchReleases();
    // 查询
    this.searchSubjection = this.searchSubject$
      .pipe(debounceTime(300))
      .pipe(distinctUntilChanged())
      .subscribe(keyword => {
        this.searchIssues = [];
        if (keyword) {
          this._githubApiService.fetchIssues(keyword).subscribe(issues => {
            this.searchIssues = issues;
          });
        }
      });
  }

  ngOnDestroy(): void {
    if (this.searchSubjection) {
      this.searchSubjection.unsubscribe();
      this.searchSubjection = null;
    }
  }
}
